import property1 from "../public/assets/Properties/property1.jpg"
import property2 from "../public/assets/Properties/property2.jpg"
import property3 from "../public/assets/Properties/property3.jpg"
import property4 from "../public/assets/Properties/property4.jpg"
import property5 from "../public/assets/Properties/property5.jpg"
import property6 from "../public/assets/Properties/property6.jpg"
import property7 from "../public/assets/Properties/property7.jpg"
import property8 from "../public/assets/Properties/property8.jpg"
import property9 from "../public/assets/Properties/property9.jpg"
import property10 from "../public/assets/Properties/property10.jpg"
import property11 from "../public/assets/Properties/property11.jpg"
import property12 from "../public/assets/Properties/property12.jpg"
import property13 from "../public/assets/Properties/property13.jpg"
import property14 from "../public/assets/Properties/property14.jpg"
import property15 from "../public/assets/Properties/property15.jpg"

export const searchBarData = [
  {
    title: "New Project",
    firstFilter: {
      firstTitle: "Min",
      min: [
        "0 L",
        "10 L",
        "20 L",
        "30 L",
        "40 L",
        "50 L",
        "60 L",
        "70 L",
        "80 L",
        "90 L",
        "1 Cr",
        "1.1 Cr",
        "1.2 Cr",
        "1.3 Cr",
        "1.4 Cr",
        "1.5 Cr",
        "1.7 Cr",
      ],
      secondTitle: "Max",
      max: [
        "1 L",
        "15 L",
        "25 L",
        "35 L",
        "45 L",
        "55 L",
        "65 L",
        "75 L",
        "85 L",
        "95 L",
        "1.5 Cr",
        "1.8 Cr",
        "2 Cr",
        "3 Cr",
        "4 Cr",
        "5 Cr",
        "6 Cr",
      ],
    },
    secondFilter: {
      firstTitle: "Property Type",
      Residential: [
        "Apartment",
        "Ind Floor",
        "Penthouse",
        "Plot",
        "Row House",
        "Studio",
        "Townhouse",
        "Villa",
        "Villament",
      ],
      Commercial: ["Commercial Plots", "Office Space", "Retail Shop"],
    },
  },
  {
    title: "Buy Property",
    
    firstFilter: {
      firstTitle: "Min",
      min: [
        "0 L",
        "10 L",
        "20 L",
        "30 L",
        "40 L",
        "50 L",
        "60 L",
        "70 L",
        "80 L",
        "90 L",
        "1 Cr",
        "1.1 Cr",
        "1.2 Cr",
        "1.3 Cr",
        "1.4 Cr",
        "1.5 Cr",
        "1.7 Cr",
      ],
      secondTitle: "Max",
      max: [
        "1 L",
        "15 L",
        "25 L",
        "35 L",
        "45 L",
        "55 L",
        "65 L",
        "75 L",
        "85 L",
        "95 L",
        "1.5 Cr",
        "1.8 Cr",
        "2 Cr",
        "3 Cr",
        "4 Cr",
        "5 Cr",
        "6 Cr",
      ],
    },
    secondFilter: {
      firstTitle: "Property Type",
      Residential: [
        "Apartment",
        "Ind Floor",
        "Penthouse",
        "Plot",
        "Row House",
        "Studio",
        "Townhouse",
        "Villa",
        "Villament",
      ],
      Commercial: ["Commercial Plots", "Office Space", "Retail Shop"],
    },
  },
  {
    title: "Rent Property",
    firstFilter: {
      firstTitle: "Min",
      min: [
        "0 L",
        "10 L",
        "20 L",
        "30 L",
        "40 L",
        "50 L",
        "60 L",
        "70 L",
        "80 L",
        "90 L",
        "1 Cr",
        "1.1 Cr",
        "1.2 Cr",
        "1.3 Cr",
        "1.4 Cr",
        "1.5 Cr",
        "1.7 Cr",
      ],
      secondTitle: "Max",
      max: [
        "1 L",
        "15 L",
        "25 L",
        "35 L",
        "45 L",
        "55 L",
        "65 L",
        "75 L",
        "85 L",
        "95 L",
        "1.5 Cr",
        "1.8 Cr",
        "2 Cr",
        "3 Cr",
        "4 Cr",
        "5 Cr",
        "6 Cr",
      ],
    },
    secondFilter: {
      firstTitle: "Property Type",
      Residential: [
        "Apartment",
        "Ind Floor",
        "Penthouse",
        "Plot",
        "Row House",
        "Studio",
        "Townhouse",
        "Villa",
        "Villament",
      ],
      Commercial: ["Commercial Plots", "Office Space", "Retail Shop"],
    },
  },
  {
    title: "Hostel/ PG",
    firstFilter: {
      firstTitle: "Min",
      min: [
        "0 L",
        "10 L",
        "20 L",
        "30 L",
        "40 L",
        "50 L",
        "60 L",
        "70 L",
        "80 L",
        "90 L",
        "1 Cr",
        "1.1 Cr",
        "1.2 Cr",
        "1.3 Cr",
        "1.4 Cr",
        "1.5 Cr",
        "1.7 Cr",
      ],
      secondTitle:"Max",
      max: [
        "1 L",
        "15 L",
        "25 L",
        "35 L",
        "45 L",
        "55 L",
        "65 L",
        "75 L",
        "85 L",
        "95 L",
        "1.5 Cr",
        "1.8 Cr",
        "2 Cr",
        "3 Cr",
        "4 Cr",
        "5 Cr",
        "6 Cr",
      ],
    },
  },
  {
    title: "Plots &Land",
    firstFilter: {
      firstTitle: "Min",
      min: [
        "0 L",
        "10 L",
        "20 L",
        "30 L",
        "40 L",
        "50 L",
        "60 L",
        "70 L",
        "80 L",
        "90 L",
        "1 Cr",
        "1.1 Cr",
        "1.2 Cr",
        "1.3 Cr",
        "1.4 Cr",
        "1.5 Cr",
        "1.7 Cr",
      ],
      secondTitle: "Max",
      max: [
        "1 L",
        "15 L",
        "25 L",
        "35 L",
        "45 L",
        "55 L",
        "65 L",
        "75 L",
        "85 L",
        "95 L",
        "1.5 Cr",
        "1.8 Cr",
        "2 Cr",
        "3 Cr",
        "4 Cr",
        "5 Cr",
        "6 Cr",
      ],
    },
  },
  {
    title: "Find Agents",
    firstFilter: {
      firstTitle: "Choose Agent",
      min: ["For New Project", "For Resale/Rental"],
    },
  },
  {
    title: "Commercial Properies",
    firstFilter: {
      firstTitle: "Buy/Lease",
      min: ["Buy", "Lease"],
    },
    secondFilter: {
      firstTitle: "Unit Type",
      Residential: [
        "Office Space",
        "Shop",
        "Land",
        "Industrial Plot",
        "Showroom",
        "Office Space in IT/SEZ",
        "Warehouse",
        "Co-working Space",
      ],
    },
  },
];

export const properties = [
    {
      id: 1,
      image:property1,
      name: "Luxury Villa in Beverly Hills",
      location: "Beverly Hills, CA",
      price: "5,000,000",
      area: "5000 sq.ft.",
      bedrooms: 5,
      bathrooms: 4,
      features: ["Swimming Pool", "Private Garden", "Modern Design"],
      city: "Los Angeles",
    },
    {
      id: 2,
      image:property2,
      name: "Beachfront Apartment",
      location: "Miami Beach, FL",
      price: "2,000,000",
      area: "2500 sq.ft.",
      bedrooms: 3,
      bathrooms: 2,
      features: ["Ocean View", "Balcony", "24/7 Security"],
      city: "Miami",
    },
    {
      id: 3,
      image:property3,
      name: "Penthouse in Manhattan",
      location: "Manhattan, NY",
      price: "8,000,000",
      area: "4000 sq.ft.",
      bedrooms: 4,
      bathrooms: 3,
      features: ["Skyline View", "Private Elevator", "Luxury Finishes"],
      city: "New York",
    },
    {
      id: 4,
      image:property4,
      name: "Modern House in San Francisco",
      location: "San Francisco, CA",
      price: "3,500,000",
      area: "3000 sq.ft.",
      bedrooms: 4,
      bathrooms: 4,
      features: ["Rooftop Terrace", "Eco-friendly", "Open Plan"],
      city: "San Francisco",
    },
    {
      id: 5,
      image:property5,
      name: "Historic Mansion in London",
      location: "London, UK",
      price: "10,000,000",
      area: "6000 sq.ft.",
      bedrooms: 6,
      bathrooms: 5,
      features: ["Private Garden", "Gated Entrance", "Library"],
      city: "London",
    },
    {
      id: 6,
      image:property6,
      name: "Stylish Loft in Paris",
      location: "Paris, France",
      price: "2,500,000",
      area: "2000 sq.ft.",
      bedrooms: 2,
      bathrooms: 2,
      features: ["Eiffel Tower View", "High Ceilings", "Balcony"],
      city: "Paris",
    },
    {
      id: 7,
      image:property7,
      name: "Country Estate in Tuscany",
      location: "Tuscany, Italy",
      price: "7,500,000",
      area: "8000 sq.ft.",
      bedrooms: 7,
      bathrooms: 6,
      features: ["Vineyard", "Olive Grove", "Historic Charm"],
      city: "Florence",
    },
    {
      id: 8,
      image:property8,
      name: "Contemporary Apartment in Berlin",
      location: "Berlin, Germany",
      price: "1,800,000",
      area: "1500 sq.ft.",
      bedrooms: 2,
      bathrooms: 1,
      features: ["City Views", "Private Balcony", "Modern Design"],
      city: "Berlin",
    },
    {
      id: 9,
      image:property9,
      name: "Secluded Cabin in Aspen",
      location: "Aspen, CO",
      price: "4,200,000",
      area: "3500 sq.ft.",
      bedrooms: 4,
      bathrooms: 3,
      features: ["Mountain Views", "Hot Tub", "Ski-In/Ski-Out"],
      city: "Aspen",
    },
    {
      id: 10,
      image: property10,
      name: "Oceanfront Villa in Malibu",
      location: "Malibu, CA",
      price: "12,000,000",
      area: "7000 sq.ft.",
      bedrooms: 5,
      bathrooms: 5,
      features: ["Infinity Pool", "Beach Access", "Gourmet Kitchen"],
      city: "Malibu",
    },
    {
      id: 11,
      image: property11,
      name: "Downtown Condo in Chicago",
      location: "Chicago, IL",
      price: "1,000,000",
      area: "1500 sq.ft.",
      bedrooms: 2,
      bathrooms: 2,
      features: ["City View", "Modern Kitchen", "Fitness Center"],
      city: "Chicago",
    },
    {
      id: 12,
      image: property12,
      name: "Mountain Lodge in Colorado",
      location: "Vail, CO",
      price: "6,000,000",
      area: "5000 sq.ft.",
      bedrooms: 5,
      bathrooms: 4,
      features: ["Ski Resort", "Sauna", "Outdoor Deck"],
      city: "Vail",
    },
    {
      id: 13,
      image: property13,
      name: "Luxury Apartment in Tokyo",
      location: "Tokyo, Japan",
      price: "4,500,000",
      area: "3000 sq.ft.",
      bedrooms: 4,
      bathrooms: 3,
      features: ["Panoramic Views", "Smart Home", "Rooftop Garden"],
      city: "Tokyo",
    },
    {
      id: 14,
      image: property14,
      name: "Beachfront Villa in Bali",
      location: "Bali, Indonesia",
      price: "3,200,000",
      area: "4000 sq.ft.",
      bedrooms: 4,
      bathrooms: 4,
      features: ["Private Pool", "Beach Access", "Tropical Garden"],
      city: "Denpasar",
    },
    {
      id: 15,
      image: property15,
      name: "Charming Cottage in the Hamptons",
      location: "Hamptons, NY",
      price: "2,800,000",
      area: "2200 sq.ft.",
      bedrooms: 3,
      bathrooms: 2,
      features: ["Private Garden", "Wooded Area", "Charming Interior"],
      city: "East Hampton",
    },
  ];

